# @name create

POST {{host}}/api/v1/products
Content-Type: application/json

{
  "name": "omen16",
  "description": "best laptop for editing",
  "category": "laptops",
  "subCategory": "technology"
}

### Get based on location model

GET {{create.response.headers.Location}}